### ISSUE TITLE
Failed at the unix-dgram@0.2.2 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by quantonganh** [winstonjs/winston-syslog#59] opened 2015-12-03 09:24 UTC
npm install winston-syslog

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-95-generic
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/bookya_api/node_modules/winston-syslog/node_modules/unix-dgram
gyp ERR! node -v v3.1.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Linux 3.2.0-95-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install" "winston-syslog"
npm ERR! node v3.1.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! unix-dgram@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unix-dgram@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the unix-dgram package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls unix-dgram
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bookya_api/npm-debug.log
```

[npm-debug.txt](https://github.com/winstonjs/winston-syslog/files/50628/npm-debug.txt)

**Comment by santigimeno** [comment] 2015-12-03 09:43
@quantonganh I don't know. It's working for me. What OS are you using? Can you try installing `unix-dgram` only in some tmp path to see if it works for you? Run: `npm install -d unix-dgram` and paste the output if it fails

**Comment by quantonganh** [comment] 2015-12-03 10:05
> What OS are you using?

```
Ubuntu 12.04.5 LTS \n \l
```

> Run: npm install -d unix-dgram and paste the output if it fails

```
gyp ERR! build error                                                                                                                                 [19/3766]
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-95-generic
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node_modules/unix-dgram
gyp ERR! node -v v3.1.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm info unix-dgram@0.2.2 Failed to exec install script
npm ERR! Linux 3.2.0-95-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install" "-d" "unix-dgram"
npm ERR! node v3.1.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! unix-dgram@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unix-dgram@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the unix-dgram package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls unix-dgram
npm ERR! There is likely additional logging output above.
npm info preuninstall unix-dgram@0.2.2
npm info uninstall unix-dgram@0.2.2
npm info postuninstall unix-dgram@0.2.2
npm ERR! Linux 3.2.0-95-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install" "-d" "unix-dgram"
npm ERR! node v3.1.0
npm ERR! npm  v2.13.3
npm ERR! path npm-debug.log.2254dc10ff7c53eaf313b28b5e68b935
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'npm-debug.log.2254dc10ff7c53eaf313b28b5e68b935' -> 'npm-debug.log'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'npm-debug.log.2254dc10ff7c53eaf313b28b5e68b935' -> 'npm-debug.log']
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'npm-debug.log.2254dc10ff7c53eaf313b28b5e68b935',
npm ERR!   dest: 'npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

[npm-debug-unix-dgram.txt](https://github.com/winstonjs/winston-syslog/files/50655/npm-debug-unix-dgram.txt)

**Comment by santigimeno** [comment] 2015-12-03 10:19
@quantonganh are you able to install other binary(C++) addons at all? What version of python and g++ do you have installed? The minimum requirements are: `https://github.com/nodejs/node/tree/v3.1.0#unix--macintosh`

**Comment by quantonganh** [comment] 2015-12-03 11:10
> are you able to install other binary(C++) addons at all?

Here're my installed packages list:

```
├── apidoc@0.13.1                                                                                                                                    [10/3884]
├── aws-sdk@2.2.20
├── babel@5.8.34
├── bcryptjs@2.3.0
├── co@4.6.0
├── config@1.17.1
├── debug@2.2.0
├── facebook-page-stats@1.1.0
├── fbgraph@1.1.0
├── got@4.2.0
├── intercom-client@2.4.0
├── istanbul@0.3.22
├── jsdoc@3.4.0
├── jsonrpc-serializer@0.1.8
├── jsrsasign@5.0.5
├── koa@0.20.0
├── koa-bodyparser@2.0.1
├── koa-compose@2.3.0
├── koa-router@4.3.2
├── layer-api@1.0.4
├── lodash@3.10.1
├── mandrill-api@1.0.45
├── mocha@2.3.4
├── mocha-jenkins-reporter@0.1.9
├── moment@2.10.6
├── mosca@0.32.1
├── node-uuid@1.4.7
├── orientjs@2.1.0
├── path-to-regexp@1.2.1
├── pg@4.4.3
├── pg-hstore@2.3.2
├── proxyquire@1.7.3
├── raven@0.8.1
├── redis@0.12.1
├── sequelize@3.14.2
├── simple-soundcloud@1.3.0
├── sinon@1.17.2
├── supertest@1.1.0
├── swig@1.4.2
├── then-redis@1.3.0
├── validator@4.3.0
├── winston@2.1.1
├── winston-graylog2@0.2.3
└── UNMET DEPENDENCY winston-syslog@^1.1.2
```

> What version of python and g++ do you have installed?

```
python -V
Python 2.7.3
```

```
g++ -v                                                                                                    [9/3941]
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languag
es=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-
included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --ena
ble-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=g
eneric --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
```

> The minimum requirements are: https://github.com/nodejs/node/tree/v3.1.0#unix--macintosh

Oh, it requires g++ 4.8?

**Comment by santigimeno** [comment] 2015-12-03 11:17
Yes. It needs a `C++ 11` compatible compiler. Anyway, just to be sure. Can you try these steps:

```
cd /tmp
git clone https://github.com/bnoordhuis/node-unix-dgram
cd node-unix-dgram
npm install -g node-gyp # probably with sudo
npm install nan bindings
node-gyp configure
node-gyp build
```

and paste the output?

**Comment by quantonganh** [comment] 2015-12-03 11:27
npm install -g node-gyp

```
/usr/bin/node-gyp -> /usr/lib/node_modules/node-gyp/bin/node-gyp.js
node-gyp@3.2.1 /usr/lib/node_modules/node-gyp
├── graceful-fs@4.1.2
├── semver@5.1.0
├── fstream@1.0.8 (inherits@2.0.1)
├── nopt@3.0.6 (abbrev@1.0.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── which@1.2.0 (is-absolute@0.1.7)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.3)
├── tar@2.2.1 (inherits@2.0.1, block-stream@0.0.8)
├── path-array@1.0.0 (array-index@0.1.1)
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@2.0.10)
├── rimraf@2.4.4 (glob@5.0.15)
├── npmlog@1.2.1 (ansi@0.3.0, are-we-there-yet@1.0.4, gauge@1.2.2)
└── request@2.67.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, stringstream@0.0.5, caseless@0.11.0, oauth-sign@0.8.0, tunnel-agent@0.4.1, isst
ream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, qs@5.2.0, combined-stream@1.0.5, tough-cookie@2.2.1, form-data@1.0.0-rc3, mime-types@2.1
.8, bl@1.0.0, hawk@3.1.2, http-signature@1.1.0, har-validator@2.0.3)
```

npm install nan bindings

```
npm WARN package.json unix-dgram@0.2.2 license should be a valid SPDX license expression
bindings@1.1.1 node_modules/bindings

nan@2.0.9 node_modules/nan
```

node-gyp configure       

```                                                                                   [1296/1357]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@3.1.0 | linux | x64
gyp http GET https://iojs.org/download/release/v3.1.0/iojs-v3.1.0-headers.tar.gz
gyp http 200 https://iojs.org/download/release/v3.1.0/iojs-v3.1.0-headers.tar.gz
gyp http GET https://iojs.org/download/release/v3.1.0/SHASUMS256.txt
gyp http 200 https://iojs.org/download/release/v3.1.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/node-unix-dgram/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/iojs-3.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/iojs-3.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/node-unix-dgram',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
```

node-gyp build             

```                                                                                 [1265/1357]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@3.1.0 | linux | x64
gyp info spawn make
make: Entering directory `/tmp/node-unix-dgram/build'
gyp   CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from /root/.node-gyp/iojs-3.1.0/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/unix_dgram.cc:5:
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:468:1: error: expected unqualified-id before ‘using’
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:499:48: error: ‘Handle’ does not name a type
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:499:48: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:499:54: error: expected ‘,’ or ‘...’ before ‘<’ token
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:520:54: error: ‘Handle’ does not name a type

...

/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7092:3: error: no matching function for call to ‘v8::ReturnValue<v8::Value>::Set(v8::Local<v8::Integer>)’
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7092:3: note: candidates are:
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:2952:40: note: template<class S> void v8::ReturnValue::Set(const v8::Persistent<S>&) [with S = S, T = v8::Value]
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:2953:40: note: template<class S> void v8::ReturnValue::Set(int) [with S = S, T = v8::Value]
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7108:6: note: void v8::ReturnValue<T>::Set(bool) [with T = v8::Value]
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7108:6: note:   no known conversion for argument 1 from ‘v8::Local<v8::Integer>’ to ‘bool’
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7079:6: note: void v8::ReturnValue<T>::Set(double) [with T = v8::Value]
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7079:6: note:   no known conversion for argument 1 from ‘v8::Local<v8::Integer>’ to ‘double’
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7085:6: note: void v8::ReturnValue<T>::Set(int32_t) [with T = v8::Value, int32_t = int]
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7085:6: note:   no known conversion for argument 1 from ‘v8::Local<v8::Integer>’ to ‘int’
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7096:6: note: void v8::ReturnValue<T>::Set(uint32_t) [with T = v8::Value, uint32_t = unsigned int]
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:7096:6: note:   no known conversion for argument 1 from ‘v8::Local<v8::Integer>’ to ‘unsigned int’
/root/.node-gyp/iojs-3.1.0/include/node/v8.h:2968:18: note: template<class S> void v8::ReturnValue::Set(S*) [with S = S, T = v8::Value]
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) cons
t’:
../node_modules/nan/nan.h:1433:3: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [Release/obj.target/unix_dgram/src/unix_dgram.o] Error 1
make: Leaving directory `/tmp/node-unix-dgram/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-95-generic
gyp ERR! command "/usr/bin/iojs" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /tmp/node-unix-dgram
gyp ERR! node -v v3.1.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```

**Comment by santigimeno** [comment] 2015-12-03 11:33
@quantonganh confirmed, you need a `C++11` capable compiler. Anyway, what underlying protocol are you planning to use with winston-syslog? udp, tcp, unix-dgram?

**Comment by quantonganh** [comment] 2015-12-03 23:39
@santigimeno: Thank you very much!

I confirmed that it worked fine on the trusty (gcc 4.8):

`npm ls`:

```
└─┬ winston-syslog@1.1.2
  ├── cycle@1.0.3
  ├── glossy@0.1.7
  └─┬ unix-dgram@0.2.2
    ├── bindings@1.1.1
    └── nan@2.0.9
```

> Anyway, what underlying protocol are you planning to use with winston-syslog? udp, tcp, unix-dgram?

It's UDP to send log messages to Graylog2 via [GELF](https://www.graylog.org/resources/gelf/).

**Comment by santigimeno** [comment] 2015-12-04 09:01
@quantonganh That's great news!
I was asking about the transport because starting with the next version (to be released soon), `unix-dgram` will be an optional dependency and you would not need to add it. See: https://github.com/winstonjs/winston-syslog/commit/8facb6d54b0d9051fb260c5370bb462e1e5c6562

**Comment by NickTomlin** [comment] 2015-12-14 15:46
Now that `1.2.0 ` is tagged would it be possible to get a corresponding release on NPM? I'm tagged to this repo currently :\

**Comment by santigimeno** [comment] 2015-12-14 15:50
@NickTomlin I'm waiting for @indexzero to publish it. I hope it's soon. :)

**Comment by santigimeno** [comment] 2015-12-15 09:51
Closing this as original issue was resolved

**Closed by santigimeno** 2015-12-15 09:51 UTC

**Comment by ngerritsen** [comment] 2018-12-04 13:07
I have this issue now too on node 10

**Comment by croraf** [comment] 2019-02-27 10:57
#99

**Comment by croraf** [comment] 2019-02-27 10:58
#99
